editable: true
page:
  title: Applications
  description: Applications are software within the game that can be downloaded using the Synchronized Transferable App Repository, or STAR App. Each application serves their own unique purpose, affecting more than just your phone. Some of these range from statistics, to ordering already experienced events, among other things.

  keywords: wiki, roblox bus simulator, roblox bus sim, roblox bus sim <categoryname>

  tags: some,tags,here,that is used by the search api
  ignore: ignore

  header:
    description: |
      !!INFOBOX TITLE:"Early Access Content / Beta Content" COLOR:"#23358C" TEXT:"*\"Careful now...\"* - Fang\nv(This page is content reserved for a future update, and is here to make editing post-update easier. Most of the info shown are with the discretion that it can and will change.)"
       Applications are software within the game that can be downloaded using the Synchronized Transferable App Repository, or STAR App. Each application serves their own unique purpose, affecting more than just your phone. Some of these range from statistics, to ordering already experienced events, among other things.
       \n\n
       Existing apps that are already pre-packaged within your phone however, are instead within the [Phone's](phone-overhauled) own page. External applications will only be displayed here.
       \n\n 
       Do note that the main currency used in all transactions are [Coins](coins), with some either being needed to download an app, or to purchase goods.

    image: ''
    imageBanner: /assets/bussim/images/banners/bus-banner.webp

attributions: []

content: |
  !!INFOBOX TITLE:"Free Applications" COLOR:"#eb4034" TEXT:"The following applications can be downloaded without an initial fee. Doesn't exempt them though from having in-app transactions."
  !!LISTITEM IMAGE:"/bussim-assets/images/applications/pears-place.webp" TITLE:"Pear's Place!" DESCRIPTION:"Pear's Place is a free external application that allows you to gain Coins as a form of currency and has an array of various hosts and quests to choose from.\n\nIt also features a totally-not shady shop, allowing you to purchase items that you have experienced within events previously... with a fee, of course." REDIRECT:"pears-place"
  !!LISTITEM IMAGE:"/bussim-assets/images/applications/rider.webp" TITLE:"Rider - For the wanderers" DESCRIPTION:"Rider is a free external application that tracks various things throughout your entire bus journey, from events, currently playing radio songs, badges, items, to even some of the most bizzare things you didn't anticipate would be on here." REDIRECT:"rider"
 
  !!INFOBOX TITLE:"Paid Applications" COLOR:"#6d6d6d" TEXT:"The following applications must be payed an intial fee prior to downloading it. Often these possess a larger, more unique function."
  !!LISTITEM IMAGE:"/bussim-assets/images/applications/caser.webp" TITLE:"Caser" DESCRIPTION:"<clr:#FFE669>(1000 Coins)\n\nThe Caser app is a paid external application within Bus Simulator that allows you to customize the casing of your phone, either by material, color, or adding a decal to it. Don't question how it works with the hyper-advanced nanotechnology. It's just how it is." REDIRECT:"caser"
  